### ISSUE TITLE
[cluster-registrator/job.yaml] Parameterizing restartPolicy and backOffLimit for nirmata-cluster-registrator job

### ISSUE THREAD

**Issue by panda** [nirmata/kyverno-charts#571]
hello!

We use the cluster-registrator helm chart for registering our clusters back to NCH and would like to add support for some additional configuration. I thought this would be a great opportunity to contribute back to open source. 

Would you be open to supporting annotations and extending a few values in the cluster registrator job?

Some ideas I had in mind:
https://github.com/nirmata/kyverno-charts/blob/main/charts/cluster-registrator/templates/job.yaml#L407-L412
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: nirmata-cluster-registrator
  namespace: {{ .Values.namespace }}
  {{- with .Values.job.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "nirmata-cluster-registrator-chart.labels" . | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: nirmata-cluster-registrator
      restartPolicy: {{ .Values.job.restartPolicy | default "Never" }}
  backoffLimit: {{ .Values.job.backoffLimit | default 0 }}
```

Supporting values.yaml snippet:
```yaml
cluster:
  name:
  type: "default-policy-manager-type"
  endpoint: ""

job:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  restartPolicy: OnFailure
  backoffLimit: 2
```

Let me know if there are any questions, happy to help.
